### ISSUE TITLE
clo.bylt.gq - Callisto PPLNS Mining Pool wth 0.5% fee

### ISSUE THREAD

**Issue by YourMomGangsta** [EthereumCommonwealth/Callisto-Website#13]
Hi!

Please add https://clo.bylt.gq/ to website.

Pool meets criteria listed.

Thanks!

**Comment by yograterol** [comment]
You need to meet the pool listing requirements https://github.com/EthereumCommonwealth/Callisto-Website/issues/5

At least 50 miners or 3Gh/s
