### ISSUE TITLE
please list clo.awesomeminers.com to your list

### ISSUE THREAD

**Issue by ericwilsondc** [EthereumCommonwealth/Callisto-Website#17]
We have brought everyone a new pool!   

Please list us on the site.  We are currently only asking for .1 % pool fee to get started.   PPLNS and a great server...

**Comment by yograterol** [comment]
You need at least 50 miners or 3Gh/s, check it out our requirements. https://github.com/EthereumCommonwealth/Callisto-Website/issues/5
