### ISSUE TITLE
Bug at main page

### ISSUE THREAD

**Issue by DuDlikSPB** [EthereumCommonwealth/Callisto-Website#19]
![screen shot on 2018-08-30 at 13 34 30](https://user-images.githubusercontent.com/37420156/44849208-b4315980-ac59-11e8-9cea-25be0f0b0177.png)

Safari Mac OS

**Comment by sampol18** [comment]
Can your share a new pic or describre the bug ? The image url is broken. @DuDlikSPB

**Comment by DuDlikSPB** [comment]
https://d.pr/i/GZrfZb try this

**Comment by sneg55** [comment]
both links don't work for me either

**Comment by DuDlikSPB** [comment]
https://drive.google.com/file/d/1YkMcIVe9HbsRssgjdDBu68J486Cxt8ge/view?usp=sharing

**Comment by sampol18** [comment]
Can not reproduce the issue.
Wich version of safari are you ussing ?   @DuDlikSPB

**Comment by DuDlikSPB** [comment]
Version 11.1.2 (13605.3.8) last one

**Comment by sampol18** [comment]
Can you check again. I make a rebuild of the project statics. Can not reproduce it.  @DuDlikSPB

**Comment by DuDlikSPB** [comment]
Fine now @sampol18

**Comment by sampol18** [comment]
Closing issue.
