### ISSUE TITLE
Audit page - add links to GitHub

### ISSUE THREAD

**Issue by DuDlikSPB** [EthereumCommonwealth/Callisto-Website#21]
![screen shot on 2018-08-30 at 13 40 53](https://user-images.githubusercontent.com/37420156/44849520-aa5c2600-ac5a-11e8-9762-c20e14b7a8e9.png)

**Comment by sampol18** [comment]
Please Can your share a new image or describe the bug. The image url is broken

**Comment by DuDlikSPB** [comment]
https://d.pr/i/zIXQQV

**Comment by sampol18** [comment]
Same problem with broken images here.

**Comment by DuDlikSPB** [comment]
https://drive.google.com/file/d/1FaLc3BthOC9OIRJ1Bm-uZIK8yfJrfwPc/view?usp=sharing

**Comment by sampol18** [comment]
Solved on PR #28
