### ISSUE TITLE
The problem with mozilla  firefox

### ISSUE THREAD

**Issue by AnatoliG** [EthereumCommonwealth/Callisto-Website#25]
I can't choose the Russian version. Scroll does not work. Scale 100%. Resolution: 1600X900.
![1](https://user-images.githubusercontent.com/42859109/44897776-260eaf00-acfd-11e8-8a56-abdb137f9864.jpg)
![2](https://user-images.githubusercontent.com/42859109/44897777-260eaf00-acfd-11e8-844b-cb07c7c387d7.jpg)

**Comment by sampol18** [comment]
@AnatoliG  Try cleaning your cache please. Yesterday i added a fix for this issue.

**Comment by sampol18** [comment]
Cache issues are solved. Now you can check new improvements on next page load
