### ISSUE TITLE
Menu button doesn't work - Chrome iOS

### ISSUE THREAD

**Issue by belgracing** [EthereumCommonwealth/Callisto-Website#26]
![image](https://user-images.githubusercontent.com/30867950/44909651-dfcf4500-ad28-11e8-96fb-4c2e285adc0c.png)

**Comment by sampol18** [comment]
Because server render Javascript interactions will not work until the page is fully loaded. 
Can you share your explorer details in order to test and check if it is a problem of our side ?
@belgracing

**Comment by belgracing** [comment]
Chrome version: 68.0.3440.83
iOS version: 11.4.1

**Comment by sampol18** [comment]
Please try again @belgracing

**Comment by belgracing** [comment]
Works now.
