### ISSUE TITLE
Bug in RoadMap

### ISSUE THREAD

**Issue by DuDlikSPB** [EthereumCommonwealth/Callisto-Website#29]
<img width="577" alt="screen shot 2018-09-03 at 09 52 23" src="https://user-images.githubusercontent.com/37420156/44974143-142c4680-af5f-11e8-89d6-cf23b2cac057.png">

**Comment by DuDlikSPB** [comment]
ETC-CLO swap... Q3 2018

**Comment by sampol18** [comment]
Issue solved in last commit.
