### ISSUE TITLE
Rules of featuring mining pools on our Website

### ISSUE THREAD

**Issue by sneg55** [EthereumCommonwealth/Callisto-Website#5]
# Rules of featuring mining pools on our Website
We are getting a lot of requests for pool listings to be added onto [our website](https://callisto.network/). Whilst we appreciate your support and effort to create mining pools for the Callisto Network, we have decided to have some ground rules for listing pool information on our website. Some pools are very professional and look after their miners, and some are not, with only a handful of miners.

Why are we coming up with rules? We only want to feature and highlight the best mining pools that also give the best customer experience for its users.

We are the first coin that has implemented such rules for our website!

## What are our rules for listing pools on our website?:

- We will feature pools that have at least 3 GH/s or 50 active miners
- If the pool has stopped working or doesn't have active miners for a while, the pool will be removed from our home page. 

If the mining pool does not meet our criteria for listing, the pool owner can list their pool at: 
https://minerpool.net/pools/callisto the submission link is the following:  https://github.com/minerpoolnet/pools 

or at: 
https://wheretomine.io/coins/callisto.html

All pools that are listed on our website will also be promoted via our social media.

If your pool meets the criteria listed above feel free to create the new issue with your info at https://github.com/EthereumCommonwealth/Callisto-Website/

Thank you

**Comment by tiotoi** [comment]
amazing! thanks

**Comment by casanovamax** [comment]
You for whom it came up? If you want to comply with your rules, then remove all the empty pools in your list !!!

**Comment by casanovamax** [comment]
I'm from the principle now I will check how you adhere to these rules!

**Comment by Shnele** [comment]
This decision leads to the centralization of the currency, this will lead to the death of CLO

**Comment by sneg55** [comment]
# Delisted Pools 
August, 30th 

## https://clopool.pro 
Pool owner created fake Callisto ANN topic on Bitcointalk, admitted that it was created with the sole purpose of advertising his pool. When the team asked him, refused to state that this in unofficial ANN topic clearly. 

![image](https://user-images.githubusercontent.com/7769371/44868000-4af01d00-ac3e-11e8-849b-7dc3d069ec9b.png)

## pool.baikalmine.com 

Pool owner has spread FUD about the coin.

**Comment by casanovamax** [comment]
Можно пояснение, какой владелец нашего пула (Байкал), что сделал???

**Comment by rewrewby** [comment]
Please restore **clopool.pro** in pool's list coz the same day we talked about making it Unofficial **WE DID IT**.
P.S. "Fake" topic was created 1 month before "Real" ANN topic for spread information about upcoming fork.
<img width="761" alt="2018-09-03 17 10 50" src="https://user-images.githubusercontent.com/9310599/44991400-91c27780-af9c-11e8-93b2-f4d9abd4bb90.png">
