### ISSUE TITLE
clo.cryptomena.io

### ISSUE THREAD

**Issue by mo9a7i** [EthereumCommonwealth/Callisto-Website#7]
Hello guys,

Here is our pool that's currently sitting at 44 GHs based of MENA
Appreciate the listing

https://clo.cryptomena.io

**Comment by mo9a7i** [comment]
Pool is at 20 GHs, your support is appreciated

**Comment by mo9a7i** [comment]
44 ghs

a little support from CLO would be nice

**Comment by sneg55** [comment]
Please check this https://github.com/EthereumCommonwealth/Callisto-Website/issues/5
