### ISSUE TITLE
callistopool.org declares 0% fee, but in fact takes 5%

### ISSUE THREAD

**Issue by alekseirubin** [EthereumCommonwealth/Callisto-Website#9]
On main page is declared 0% fee, but this wallet with 0 hashrate and workers gets 5% reward from every block: http://callistopool.org/#/account/0x36c95c9808e223749003a5ccb2a4c2a797cb7cf3

**Comment by DuDlikSPB** [comment]
И все похуй ГОД!

**Comment by oneevil** [comment]
Epic fail %)
